"""Apply Phase 5 knowledge patches to knowledge/gita/verses.json.

Two merges, both idempotent and rebuild-safe (run this after the Phase 1
chain: build_spine -> enrich_tier_a -> build_taxonomy -> build_chunks):

  1. contested_overrides_v5.json  — contested flags, pluralism notes,
     do_not_use_when corrections found in the Phase 5 audit.
  2. tier_a_hi.json               — Hindi translations for tier-A cards.

Usage:
    python scripts/apply_phase5_patches.py
    python scripts/apply_phase5_patches.py --dry-run
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
VERSES = ROOT / "knowledge" / "gita" / "verses.json"
CONTESTED = ROOT / "knowledge" / "gita" / "contested_overrides_v5.json"
TIER_A_HI = ROOT / "knowledge" / "gita" / "tier_a_hi.json"
HI_GAPS = ROOT / "knowledge" / "validation" / "hi_gaps.md"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    doc = json.loads(VERSES.read_text(encoding="utf-8"))
    cards = doc["verses"] if isinstance(doc, dict) else doc
    by_id = {c["id"]: c for c in cards}

    contested_applied = 0
    hi_applied = 0
    missing: list[str] = []

    # --- 1. contested overrides ---
    if CONTESTED.exists():
        patches = json.loads(CONTESTED.read_text(encoding="utf-8")).get("patches", {})
        for verse_id, fields in patches.items():
            card = by_id.get(verse_id)
            if card is None:
                missing.append(verse_id)
                continue
            for key, value in fields.items():
                card[key] = value
            contested_applied += 1

    # --- 2. tier-A Hindi ---
    if TIER_A_HI.exists():
        hi_doc = json.loads(TIER_A_HI.read_text(encoding="utf-8"))
        source_label = hi_doc.get("hi_source", "curated_v5")
        for verse_id, hi_text in hi_doc.get("translations", {}).items():
            card = by_id.get(verse_id)
            if card is None:
                missing.append(verse_id)
                continue
            if not (hi_text or "").strip():
                continue
            translations = card.setdefault("translations", {})
            translations["hi"] = hi_text
            translations.setdefault("hi_by_source", {})[source_label] = hi_text
            hi_applied += 1

    if missing:
        print(f"ERROR: unknown verse ids in patch files: {sorted(set(missing))}")
        sys.exit(1)

    print(f"contested overrides applied: {contested_applied}")
    print(f"tier-A hindi translations applied: {hi_applied}")

    # --- report remaining tier-A HI gaps ---
    tier_a = [c for c in cards if c.get("quality") == "tier_a"]
    gaps = [
        c["id"]
        for c in tier_a
        if not (c.get("translations", {}).get("hi") or "").strip()
    ]
    print(f"tier-A total: {len(tier_a)}, still missing HI: {len(gaps)}")

    if args.dry_run:
        print("\n(dry run — nothing written)")
        return

    VERSES.write_text(
        json.dumps(doc, ensure_ascii=False, indent=2), encoding="utf-8"
    )
    print(f"wrote {VERSES}")

    _write_gap_report(len(tier_a), gaps)
    print(f"wrote {HI_GAPS}")


def _write_gap_report(tier_a_total: int, gaps: list[str]) -> None:
    filled = tier_a_total - len(gaps)
    lines = [
        "# Hindi coverage gaps (tier-A)",
        "",
        "Regenerated by `scripts/apply_phase5_patches.py`.",
        "",
        f"- tier-A cards: **{tier_a_total}**",
        f"- with `translations.hi`: **{filled}**",
        f"- still missing: **{len(gaps)}**",
        "",
    ]
    if gaps:
        lines += [
            "## Remaining",
            "",
            "Add these to `knowledge/gita/tier_a_hi.json` and re-run the script.",
            "",
        ]
        lines += [f"- `{vid}`" for vid in gaps]
    else:
        lines.append("**All tier-A cards have a Hindi translation.**")
    lines.append("")
    HI_GAPS.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
